[package]
name = "simple-web-app"
version = "0.1.0"
edition = "2021"
author = "Pietra Ferreira <piferreira@icloud.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
chrono = "0.2"
clap = "*"
